In [2]:
import pandas as pd

# Load Dataset
dataset_training = pd.read_csv('data_training_praktikum.csv')
dataset.describe(include='all')

dataset_testing = pd.read_csv('data_testing_praktikum_tanpakelas.csv')

In [9]:
# Describe all columns
for i in range (60):
    print(dataset[dataset.columns[i]].describe())
    print()

count    12594.000000
mean         0.237891
std          0.425809
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: cont1, dtype: float64

count    12594.000000
mean         0.526044
std          0.499341
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: cont2a, dtype: float64

count    12594.000000
mean         0.328331
std          0.469625
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: cont3, dtype: float64

count     12594
unique       10
top           F
freq       5029
Name: loc, dtype: object

count        12594
unique           7
top       last_stc
freq          2077
Name: struct1, dtype: object

count     12594
unique        3
top       Final
freq       5232
Name: struct2, dtype: object

count               12594
unique                 17
top       NonPrototypical
freq                 3067
Name: struct3, dtype: object

count    12594.000000
mean         0.241861
std          0.428228
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: length, dtype: float64

count     12594
unique        3
top        None
freq      11331
Name: cit1, dtype: object

count     12594
unique        4
top        None
freq      11331
Name: cit2, dtype: object

count    12594.000000
mean         0.592266
std          0.491433
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: syn, dtype: float64

count    12594.000000
mean         0.089011
std          0.284770
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: adj, dtype: float64

count    12594.000000
mean         0.000873
std          0.029542
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: affect_formulaic, dtype: float64

count    12594.000000
mean         0.063522
std          0.243910
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: bad_formulaic, dtype: float64

count    12594.000000
mean         0.001667
std          0.040802
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: comparison_formulaic, dtype: float64

count    12594.000000
mean         0.000159
std          0.012601
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: continue_formulaic, dtype: float64

count    12594.000000
mean         0.034540
std          0.182619
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: contrast_formulaic, dtype: float64

count    12594.000000
mean         0.009370
std          0.096346
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: detail_formulaic, dtype: float64

count    12594.000000
mean         0.005320
std          0.072747
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: future_formulaic, dtype: float64

count    12594.000000
mean         0.001429
std          0.037780
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: gap_formulaic, dtype: float64

count    12594.000000
mean         0.148007
std          0.355121
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: good_formulaic, dtype: float64

count    12594.000000
mean         0.022392
std          0.147959
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: here_formulaic, dtype: float64

count    12594.000000
mean         0.013260
std          0.114392
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: in_order_to_formulaic, dtype: float64

count    12594.000000
mean         0.034540
std          0.182619
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: method_formulaic, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: no_textstructure_formulaic, dtype: float64

count    12594.000000
mean         0.003097
std          0.055564
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: similarity_formulaic, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: them_formulaic, dtype: float64

count    12594.000000
mean         0.000556
std          0.023570
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: textstructure_formulaic, dtype: float64

count    12594.000000
mean         0.070033
std          0.255213
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: tradition_formulaic, dtype: float64

count    12594.000000
mean         0.000635
std          0.025197
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: us_previous_formulaic, dtype: float64

count    12594.000000
mean         0.015245
std          0.122532
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: problem_formulaic, dtype: float64

count    12594.000000
mean         0.015722
std          0.124402
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: solution_formulaic, dtype: float64

count    12594.000000
mean         0.010481
std          0.101844
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: our_aim_formulaic, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: affect, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: argumentation, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: better_solution, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: change, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: comparison, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: continue, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: contrast, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: interest, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: need, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: presentation, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: problem, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: research, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: solution, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: textstructure, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: use, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: copula, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: aim_ref_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: gap_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: general_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: ref_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: ref_us_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: textstructure_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: them_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: them_pronoun_agent, dtype: float64

count    12594.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: us_agent, dtype: float64

count    12594.000000
mean         0.077656
std          0.267640
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: negation, dtype: float64

count        12594
unique          16
top       own_mthd
freq          4844
Name: labelclass, dtype: object

In [44]:
# Select all Categorical columns and print frequency
nominal = dataset.select_dtypes(include=['object'])
for i in range (7):
    print(nominal[nominal.columns[i]].value_counts())
    print()

F    5029
G    1268
E    1259
H    1252
J     677
B     634
D     634
I     630
C     627
A     584
Name: loc, dtype: int64

last_stc                    2077
second_or_third_last_stc    1808
second_or_third_stc         1808
second_third                1800
first_third                 1796
last_third                  1796
first_stc                   1509
Name: struct1, dtype: int64

Final      5232
Medial     4218
Initial    3144
Name: struct2, dtype: int64

NonPrototypical    3067
Introduction       1995
Method             1740
Experiment         1170
Result              760
Related Work        649
Conclusion          604
Abstract            578
Discussion          418
Data                409
Evaluation          360
Solution            313
Implementation      247
Problem             134
Example             104
Further Work         38
Limitation            8
Name: struct3, dtype: int64

None             11331
Citation          1082
Self Citation      181
Name: cit1, dtype: int64

None         11331
End            656
Beginning      319
Middle         288
Name: cit2, dtype: int64

own_mthd    4844
othr        1605
use          954
own_conc     941
support      634
co_gro       602
textual      594
gap_weak     445
own_res      389
prev_own     383
aim          350
nov_adv      278
codi         201
fut          156
antisupp     109
own_fail     109
Name: labelclass, dtype: int64

In [43]:
# Drop Columns with mean = 0
list_column = []
import numpy as np
for i in range (60):
    if (dataset[dataset.columns[i]].dtype != np.object and dataset[dataset.columns[i]].mean() == 0):
        list_column.append(dataset.columns[i])
        
dropped_dataset = dataset
for column in list_column:
    dropped_dataset = dropped_dataset.drop(column,axis=1)
    
print(dropped_dataset.describe(include ='all'))

               cont1        cont2a         cont3    loc   struct1 struct2  \
count   12594.000000  12594.000000  12594.000000  12594     12594   12594
unique           NaN           NaN           NaN     10         7       3
top              NaN           NaN           NaN      F  last_stc   Final
freq             NaN           NaN           NaN   5029      2077    5232
mean        0.237891      0.526044      0.328331    NaN       NaN     NaN
std         0.425809      0.499341      0.469625    NaN       NaN     NaN
min         0.000000      0.000000      0.000000    NaN       NaN     NaN
25%         0.000000      0.000000      0.000000    NaN       NaN     NaN
50%         0.000000      1.000000      0.000000    NaN       NaN     NaN
75%         0.000000      1.000000      1.000000    NaN       NaN     NaN
max         1.000000      1.000000      1.000000    NaN       NaN     NaN

                struct3        length   cit1   cit2     ...      \
count             12594  12594.000000  12594  12594     ...
unique               17           NaN      3      4     ...
top     NonPrototypical           NaN   None   None     ...
freq               3067           NaN  11331  11331     ...
mean                NaN      0.241861    NaN    NaN     ...
std                 NaN      0.428228    NaN    NaN     ...
min                 NaN      0.000000    NaN    NaN     ...
25%                 NaN      0.000000    NaN    NaN     ...
50%                 NaN      0.000000    NaN    NaN     ...
75%                 NaN      0.000000    NaN    NaN     ...
max                 NaN      1.000000    NaN    NaN     ...

        method_formulaic  similarity_formulaic  textstructure_formulaic  \
count       12594.000000          12594.000000             12594.000000
unique               NaN                   NaN                      NaN
top                  NaN                   NaN                      NaN
freq                 NaN                   NaN                      NaN
mean            0.034540              0.003097                 0.000556
std             0.182619              0.055564                 0.023570
min             0.000000              0.000000                 0.000000
25%             0.000000              0.000000                 0.000000
50%             0.000000              0.000000                 0.000000
75%             0.000000              0.000000                 0.000000
max             1.000000              1.000000                 1.000000

        tradition_formulaic  us_previous_formulaic  problem_formulaic  \
count          12594.000000           12594.000000       12594.000000
unique                  NaN                    NaN                NaN
top                     NaN                    NaN                NaN
freq                    NaN                    NaN                NaN
mean               0.070033               0.000635           0.015245
std                0.255213               0.025197           0.122532
min                0.000000               0.000000           0.000000
25%                0.000000               0.000000           0.000000
50%                0.000000               0.000000           0.000000
75%                0.000000               0.000000           0.000000
max                1.000000               1.000000           1.000000

        solution_formulaic  our_aim_formulaic      negation  labelclass
count         12594.000000       12594.000000  12594.000000       12594
unique                 NaN                NaN           NaN          16
top                    NaN                NaN           NaN    own_mthd
freq                   NaN                NaN           NaN        4844
mean              0.015722           0.010481      0.077656         NaN
std               0.124402           0.101844      0.267640         NaN
min               0.000000           0.000000      0.000000         NaN
25%               0.000000           0.000000      0.000000         NaN
50%               0.000000           0.000000      0.000000         NaN
75%               0.000000           0.000000      0.000000         NaN
max               1.000000           1.000000      1.000000         NaN

[11 rows x 33 columns]

In [20]:
# Encode Categorical Column using One-Hot Encoder
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
encoded_dataset = enc.fit_transform(dataset)

print(type(encoded_dataset))

<class 'scipy.sparse.csr.csr_matrix'>